# Generated by Django 3.2.5 on 2021-08-31 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.doctor')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=200)),
                ('medical_comment', models.TextField()),
                ('medtech_comment', models.TextField()),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.doctor')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.hospital')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='hid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.hospital'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.user'),
        ),
    ]
